FROM ros:dashing-ros-core

RUN apt-get update && apt-get install -y \
    build-essential clang-format python3-colcon-common-extensions python3-rosdep

# Create ROS workspace
WORKDIR /ws
COPY . /ws/src/phidgets_drivers

# Use rosdep to install all dependencies (including ROS itself)
RUN rosdep init && rosdep update && rosdep install --from-paths src -i -y --rosdistro dashing

RUN /bin/bash -c "source /opt/ros/dashing/setup.bash && \
    colcon build --parallel-workers 1 --packages-select libphidget22"
